server:
  port: 8086


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erupt?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

erupt:
  # 是否开启csrf防御
  csrf-inspect: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
  redis-session: false
  # redis session是否自动续期，1.10.8及以上版本支持
  redis-session-refresh: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  upload-path: D:/erupt/pictures
  # 是否保留上传文件原始名称
  keep-upload-file-name: false
  # 项目初始化方式，NONE 不执行初始化代码、EVERY 每次启动都进行初始化、FILE 通过标识文件判断是否需要初始化
  init-method-enum: FILE
  # 默认语言，1.12.3及以上版本支持
  default-locales: zh-CN
