server:
  port: 8081

ws:
  host: 0.0.0.0
  port: 8082
  #client开放指定信息给服务器看
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

integration-export:
  enable: true
integration-wechat:
  enable: true
integration-event:
  enable: false

event:
    publishProperties:
      - appKey: "p1"
        topic: "t1"
        className: "ddd"
        publishType: "local"
    consumerProperties:
      - appKey: "c1"
        topic: "t2"
        consumerGroup: "cg"
        tag:
          - helo
          - word

limit:
  local: false
  redis: false

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    password: jxp550
  boot:
    admin:
      client:
        url: http://localhost:8081

  application:
    name: spring-boot-test1

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

elasticsearch:
  e

milton:
  filesystem_root: /tmp
  exclude_paths:
    - /static
    - /templates
    - /management
    - /webjars