server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

integration-export:
  enable: true
integration-wechat:
  enable: true
integration-event:
  enable: true

event:
    publishProperties:
      - appKey: "p1"
        topic: "t1"
        className: "ddd"
        publishType: "local"
    consumerProperties:
      - appKey: "c1"
        topic: "t2"
        consumerGroup: "cg"
        tag:
          - helo
          - word

limit:
  local: true
  redis: true

spring:
  main:
    allow-bean-definition-overriding: true