server:
  port: 8083
  servlet:
    context-path: /case/api
netty:
  websocket:
    ip: localhost
    port: 3333
    path: /ws
    max-frame-size: 10240

liteflow:
  #规则文件路径，只要使用规则，则必须配置rule-source配置，但是如果你是用代码动态构建规则，则rule-source自动失效。
  rule-source: liteflow/*.el.xml